source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'MJExceptionReportKit_Example' do
  pod 'MJExceptionReportKit', :path => '../'
#  pod 'MJExceptionReportKit_Source', :path => '../'

  target 'MJExceptionReportKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
