use_frameworks!

platform :ios, '10.0'

target 'MJExceptionReportKit_Example' do
  pod 'MJExceptionReportKit', :path => '../'

  target 'MJExceptionReportKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
